config/routes.rb
Rails.application.routes.draw do
  resources :ads

  root 'ads#index'
end

app/models/ad.rb
class Ad < ActiveRecord::Base
  has_many :creatives, inverse_of: :ad
  has_many :targetings, inverse_of: :ad

  validates :budget,
    presence: true,
    numericality: { greater_than: 0 }

  validates :creatives,
    presence: true

  validates :targetings,
    presence: true

  accepts_nested_attributes_for :creatives, reject_if: :all_blank
  accepts_nested_attributes_for :targetings, reject_if: :all_blank
end

app/models/creative.rb
class Creative < ActiveRecord::Base
  belongs_to :ad, inverse_of: :creatives

  validates :bid,
    presence: true,
    numericality: {
      greater_than: 0,
      less_than_or_equal_to: lambda { |creative| creative.ad.budget }
    }

  validates :ad_text,
    presence: true
end

app/models/targeting.rb
class Targeting < ActiveRecord::Base
  belongs_to :ad, inverse_of: :targetings

  enum gender: [:male, :female, :unkown]

  validate :has_at_least_one_target?

  validates :places,
    allow_blank: true,
    format: {
      with: /\A([a-z]+)(,\s*[a-z]+)*\z/i,
      message: 'Must use only comma-separated single-word places with alphabetic characters'
    }

  validates :gender,
    inclusion: { in: genders.keys }


  def has_at_least_one_target?
    if places.blank? and gender == 'unkown'
      errors.add :places, 'No target specified'
      errors.add :gender, 'No target specified'
    end
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  def index
    @ads = Ad.page(params[:page]).per(10)
  end

  def show
    @ad = Ad.find params[:id]
    render :edit
  end

  def new
    @ad = Ad.new
    @ad.creatives.build
    @ad.targetings.build
  end

  def edit
    @ad = Ad.find params[:id]
  end

  def create
    @ad = Ad.new ad_params

    if @ad.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def update
    @ad = Ad.find params[:id]

    if @ad.update ad_params
      redirect_to action: :index
    else
      render :edit
    end
  end

  private
    def ad_params
      params.require(:ad).permit(
        :budget,
        :creatives_attributes => [:id, :bid, :ad_text],
        :targetings_attributes => [:id, :places, :gender]
      )
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ads/_form.html.erb
<div class="col-md-12">
  <%= simple_nested_form_for @ad, html: {id: 'ad-form', class: 'form-horizontal'},
    wrapper: :horizontal_form do |f| %>
    <!-- Error indication -->
    <%= f.error_notification %>

    <!-- Ad fields -->
    <div class="row">
        <%= f.input :budget, wrapper: :horizontal_input_group do %>
          <span class="input-group-addon">$</span>
          <%= f.input_field :budget, input_html: { min: "0.01", step: "0.1" },
            class: "form-control" %>
        <% end %>
    </div>

    <!-- Creative and Target headers -->
    <div class="row">
      <div class="col-md-6">
        <h2 class="text-center">Creatives</h2>
      </div>
      <div class="col-md-6">
        <h2 class="text-center">Targetings</h2>
      </div>
    </div>

    <div class="row">
      <!-- Creative fields -->
      <div class="col-md-6">
        <%= f.simple_fields_for :creatives, wrapper: :horizontal_input_group,
          html: {class: "form-horizontal"} do |ff| %>
          <div class="row">
            <div id="creatives" class="col-md-12">
              <%= ff.input :bid, wrapper: :horizontal_input_group do %>
                <span class="input-group-addon">$</span>
                <%= ff.input_field :bid, input_html: { min: "0.001", step: "0.1" },
                  class: "form-control" %>
              <% end %>
              <%= ff.input :ad_text, as: :string, wrapper: :horizontal_input_group,
                input_html: { placeholder: 'Fill with the text of this ad' } %>
              <hr>
            </div>
          </div>
        <% end %>

        <div class="row text-center">
          <%= f.link_to_add "More creatives", :creatives,
            data: { target: "#creatives" }, class: "btn btn-default" %>
        </div>
      </div>

      <!-- Targeting fields -->
      <div class="col-md-6">
        <%= f.simple_fields_for :targetings, wrapper: :horizontal_input_group,
          html: {class: "form-horizontal"} do |ff| %>
          <div class="row">
            <div id="targetings" class="col-md-12">
              <%= ff.input :places, as: :string, input_html: {
                  placeholder: 'Houston, Caracas, Recife',
                  pattern: "^([a-zA-Z]+)(,\s*[a-zA-Z]+)*$"
              } %>
              <% if @ad.new_record? %>
                <%= ff.input :gender,
                  collection: Targeting.genders.keys.map { |w| [w.humanize, w] },
                  selected: :unkown, include_blank: true %>
              <% else %>
                <%= ff.input :gender,
                  collection: Targeting.genders.keys.map { |w| [w.humanize, w] },
                  include_blank: true %>
              <% end %>
              <hr>
            </div>
          </div>
        <% end %>

        <div class="row text-center">
          <%= f.link_to_add "More targetings", :targetings,
            data: { target: "#targetings" }, class: "btn btn-default" %>
        </div>
      </div>
    </div>

    <!-- Submit button -->
    <div class="row">
      <div class="col-md-12">
        <%= f.submit (@ad.new_record? ? 'Create' : 'Update'),
          class: "btn btn-primary btn-lg center-block" %>
      </div>
    </div>
  <% end %>
</div>

app/views/ads/_header.html.erb
<div class="col-md-12 page-header">
  <h1 class="text-center"><%= title %></h1>
  <%= yield %>
</div>

app/views/ads/edit.html.erb
<div class="row">
  <%= render layout: 'header', locals: { title: 'Edit Ad'} do %>
    <%= link_to ads_path, class: "btn btn-default" do %>
      <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Back
    <% end %>
  <% end %>

  <%= render 'form' %>
</div>

app/views/ads/index.html.erb
<div class="row">
  <%= render layout: 'header', locals: { title: 'Ads List'} do %>
    <%= link_to new_ad_path, class: "btn btn-default btn-new-ad" do %>
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Create Ad
    <% end %>
  <% end %>
</div>

<% @ads.each do |ad| %>
  <%= link_to edit_ad_path(ad), class: 'link-wrapper' do %>
    <div class="row ad-list-row">
      <div class="col-md-1">
        <h2><%= ad.id %>.</h2>
      </div>
      <div class="col-md-5 text-center">
        <h2>$<%= ad.budget %></h2>
      </div>
      <div class="col-md-3 text-center">
        <h2>Creatives: <%= ad.creatives.count %></h2>
      </div>
      <div class="col-md-3 text-center">
        <h2>Targetings: <%= ad.targetings.count %></h2>
      </div>
    </div>
  <% end %>
<% end %>

<div class="row">
  <div class="col-md-12 text-center">
    <%= paginate @ads %>
  </div>
</div>

app/views/ads/new.html.erb
<div class="row">
  <%= render layout: 'header', locals: { title: 'New Ad'} do %>
    <%= link_to ads_path, class: "btn btn-default" do %>
      <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Back
    <% end %>
  <% end %>

  <%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>MiniAds</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>